### ISSUE TITLE
Speech is not a function

### ISSUE THREAD

**Issue by markuspetzke** [txie1993/mallard#1]
Hey, 
Every time I start my bot I get that error.
```
const speechClient = Speech({ projectId: projectId });
                     ^

TypeError: Speech is not a function
    at Object.<anonymous> (c:\Users\Markus\Desktop\AalBot\Voice\Bot.js:9:22)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:826:3)
```

**Comment by markuspetzke** [comment]
The Code got not changed
